[build-system]
requires = ["setuptools>=60"]
build-backend = "setuptools.build_meta"

[tool.towncrier]
directory = "changes"
package = "toga"
package_dir = "src"
filename = "docs/background/releases.rst"
title_format = "{version} ({project_date})"
template = "changes/template.rst"
