# The coverage settings in this file only control `coverage combine` and `coverage report`.
# `coverage run` is controlled by the pyproject.toml files in each package's subdirectory.

[tool.coverage.run]
relative_files = true

# In each subdirectory's pyproject.toml, we use both of the following settings:
#   * `source_pkgs`: detects the given packages no matter where they're imported from.
#   * `source`: detects all files in the given directory, including files that are
#      never imported by the tests.
#
# When running through `tox`, this will produce duplicate entries which must be merged
# with `coverage combine` using the lists below. In each list, the first item is a path to
# a source code directory, and the other items are paths in the coverage data which will
# be mapped to that directory. The order of the lists is significant, but their names are
# not.
[tool.coverage.paths]
android = [
    "android/src/toga_android",
    "**/toga_android",
]
cocoa = [
    "cocoa/src/toga_cocoa",
    "**/toga_cocoa",
]
dummy = [
    "dummy/src/toga_dummy",
    "**/toga_dummy",
]
gtk = [
    "gtk/src/toga_gtk",
    "**/toga_gtk",
]
iOS = [
    "iOS/src/toga_iOS",
    "**/toga_iOS",
]
web = [
    "web/src/toga_web",
    "**/toga_web",
]
winforms = [
    "winforms/src/toga_winforms",
    "**/toga_winforms",
]
# This one must come last, otherwise the wildcard would match too much, because the
# repository root directory is probably also called "toga".
core = [
    "core/src/toga",
    "**/toga",
]

[tool.coverage.report]
show_missing = true
skip_covered = true
skip_empty = true
precision = 1
exclude_lines = [
    "pragma: no cover",
    "@(abc\\.)?abstractmethod",
    "NotImplementedError\\(\\)"
]

[tool.isort]
profile = "black"
split_on_trailing_comma = true
combine_as_imports = true
known_first_party = [
    "toga",
    "toga_android",
    "toga_cocoa",
    "toga_dummy",
    "toga_gtk",
    "toga_iOS",
    "toga_web",
    "toga_winforms",
]

[tool.towncrier]
directory = "changes"
package = "toga"
package_dir = "src"
filename = "docs/background/releases.rst"
title_format = "{version} ({project_date})"
template = "changes/template.rst"
