[build-system]
requires = ["setuptools>=60"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
skip_glob = [
    "docs/conf.py",
    "venv*",
    "local",
]
known_first_party = [
    "toga_android",
    "toga_cocoa",
    "toga_dummy",
    "toga_gtk",
    "toga_iOS",
    "toga_web",
    "toga_winforms"
]
