[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Demo One Window"
bundle = "org.beeware"
version = "0.3.0.dev37"
url = "https://beeware.org"
license = "BSD license"
author = 'Tiberius Yak'
author_email = "tiberius@beeware.org"

[tool.briefcase.app.one_window]
formal_name = "Demo One Window"
description = "A testing app"
sources = ['one_window']
requires = [
    '../../src/core',
]


[tool.briefcase.app.one_window.macOS]
requires = [
    '../../src/cocoa',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.one_window.linux]
requires = [
    '../../src/gtk',
]

[tool.briefcase.app.one_window.windows]
requires = [
    '../../src/winforms',
]

# Mobile deployments
[tool.briefcase.app.one_window.iOS]
requires = [
    '../../src/iOS',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.one_window.android]
requires = [
    '../../src/android',
]
