[build-system]
requires = ["setuptools>=60"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
parallel = true
branch = true
relative_files = true

# See notes in the root pyproject.toml file.
source = ["src", "../dummy/src"]
source_pkgs = ["toga", "toga_dummy"]
