[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Date Picker Example"
bundle = "org.beeware"
version = "0.3.0.dev31"
url = "https://beeware.org"
license = "BSD license"
author = 'Tiberius Yak'
author_email = "tiberius@beeware.org"

[tool.briefcase.app.datepicker]
formal_name = "Date Picker Example"
description = "A testing app"
sources = ['datepicker']
requires = [
    '../../src/core',
]


[tool.briefcase.app.datepicker.macOS]
requires = [
    '../../src/cocoa',
]

[tool.briefcase.app.datepicker.linux]
requires = [
    '../../src/gtk',
]

[tool.briefcase.app.datepicker.windows]
requires = [
    '../../src/winforms',
]

# Mobile deployments
[tool.briefcase.app.datepicker.iOS]
requires = [
    '../../src/iOS',
]

[tool.briefcase.app.datepicker.android]
requires = [
    '../../src/android',
]
